import React from 'react';

const ResumeForm = ({ resumeData, onChange, onExperienceAdd, onExperienceDelete, onEducationAdd, onEducationDelete, onAiSuggest, isAiLoading, onCustomSectionAdd, onCustomSectionDelete }) => {
  const { personalInfo, experience, education, skills, customSections } = resumeData;

  return (
    <div>
      {/* ... Personal Info, Experience, Education, and Skills sections (code is unchanged) ... */}
      <div className="mb-8"><h3 className="text-lg font-semibold text-gray-800 mb-4 border-b pb-2">Personal Information</h3><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><input type="text" name="name" placeholder="Full Name" value={personalInfo.name} onChange={(e) => onChange('personalInfo', 'name', e.target.value)} className="p-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none"/><input type="email" name="email" placeholder="Email" value={personalInfo.email} onChange={(e) => onChange('personalInfo', 'email', e.target.value)} className="p-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none"/><input type="tel" name="phone" placeholder="Phone Number" value={personalInfo.phone} onChange={(e) => onChange('personalInfo', 'phone', e.target.value)} className="p-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none"/><input type="text" name="linkedin" placeholder="LinkedIn Profile URL" value={personalInfo.linkedin} onChange={(e) => onChange('personalInfo', 'linkedin', e.target.value)} className="p-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none"/><div className="col-span-2"><input type="text" name="github" placeholder="GitHub Profile URL" value={personalInfo.github} onChange={(e) => onChange('personalInfo', 'github', e.target.value)} className="p-2 border border-gray-300 rounded-md w-full focus:ring-2 focus:ring-blue-500 focus:outline-none"/></div></div></div>
      <div className="mb-8"><h3 className="text-lg font-semibold text-gray-800 mb-4 border-b pb-2">Experience</h3>{experience.map((exp, index) => (<div key={index} className="mb-4 p-4 border border-gray-200 rounded-lg relative"><button type="button" onClick={() => onExperienceDelete(index)} className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full w-6 h-6 flex items-center justify-center font-bold hover:bg-red-700">&times;</button><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><input type="text" placeholder="Role / Title" value={exp.role} onChange={(e) => onChange('experience', 'role', e.target.value, index)} className="p-2 border border-gray-300 rounded-md"/><input type="text" placeholder="Company" value={exp.company} onChange={(e) => onChange('experience', 'company', e.target.value, index)} className="p-2 border border-gray-300 rounded-md"/><input type="text" placeholder="Start Date (e.g., 2023-01)" value={exp.startDate} onChange={(e) => onChange('experience', 'startDate', e.target.value, index)} className="p-2 border border-gray-300 rounded-md"/><input type="text" placeholder="End Date (e.g., Present)" value={exp.endDate} onChange={(e) => onChange('experience', 'endDate', e.target.value, index)} className="p-2 border border-gray-300 rounded-md"/><div className="relative col-span-2"><textarea placeholder="Job Description" value={exp.description} onChange={(e) => onChange('experience', 'description', e.target.value, index)} className="p-2 pr-24 border border-gray-300 rounded-md w-full" rows="5"/><button type="button" onClick={() => onAiSuggest(exp.description, index)} disabled={isAiLoading} className="absolute bottom-2 right-2 bg-gradient-to-r from-purple-500 to-indigo-600 text-white text-xs font-bold py-1 px-2 rounded-md hover:from-purple-600 hover:to-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed">{isAiLoading ? 'Thinking...' : '✨ AI Suggest'}</button></div></div></div>))}<button type="button" onClick={onExperienceAdd} className="mt-2 w-full bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md">Add Experience</button></div>
      <div className="mb-8"><h3 className="text-lg font-semibold text-gray-800 mb-4 border-b pb-2">Education</h3>{education.map((edu, index) => (<div key={index} className="mb-4 p-4 border border-gray-200 rounded-lg relative"><button type="button" onClick={() => onEducationDelete(index)} className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full w-6 h-6 flex items-center justify-center font-bold hover:bg-red-700">&times;</button><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><input type="text" placeholder="Institution" value={edu.institution} onChange={(e) => onChange('education', 'institution', e.target.value, index)} className="p-2 border border-gray-300 rounded-md col-span-2"/><input type="text" placeholder="Degree (e.g., B.S. in Computer Science)" value={edu.degree} onChange={(e) => onChange('education', 'degree', e.target.value, index)} className="p-2 border border-gray-300 rounded-md"/><input type="text" placeholder="Graduation Date (e.g., 2022-12)" value={edu.graduationDate} onChange={(e) => onChange('education', 'graduationDate', e.target.value, index)} className="p-2 border border-gray-300 rounded-md"/><input type="text" placeholder="GPA (optional)" value={edu.gpa} onChange={(e) => onChange('education', 'gpa', e.target.value, index)} className="p-2 border border-gray-300 rounded-md"/></div></div>))}<button type="button" onClick={onEducationAdd} className="mt-2 w-full bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded-md">Add Education</button></div>
      <div><h3 className="text-lg font-semibold text-gray-800 mb-4 border-b pb-2">Skills</h3><textarea placeholder="Your skills, separated by commas" value={skills} onChange={(e) => onChange('skills', null, e.target.value)} className="p-2 border border-gray-300 rounded-md w-full" rows="4"/></div>

      {/* NEW: Custom Sections Form */}
      <div className="mt-8">
        <h3 className="text-lg font-semibold text-gray-800 mb-4 border-b pb-2">Custom Sections</h3>
        {customSections.map((section, index) => (
          <div key={index} className="mb-4 p-4 border border-gray-200 rounded-lg relative">
            <button type="button" onClick={() => onCustomSectionDelete(index)} className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full w-6 h-6 flex items-center justify-center font-bold hover:bg-red-700">&times;</button>
            <div className="grid grid-cols-1 gap-4">
              <input type="text" placeholder="Section Title (e.g., Projects)" value={section.title} onChange={(e) => onChange('customSections', 'title', e.target.value, index)} className="p-2 border border-gray-300 rounded-md font-bold"/>
              <textarea placeholder="Section Content" value={section.content} onChange={(e) => onChange('customSections', 'content', e.target.value, index)} className="p-2 border border-gray-300 rounded-md" rows="5"/>
            </div>
          </div>
        ))}
        <button type="button" onClick={onCustomSectionAdd} className="mt-2 w-full bg-gray-600 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded-md">Add Custom Section</button>
      </div>
    </div>
  );
};

export default ResumeForm;